# TheWalls 战墙插件配置文件

# 是否已完成设置 (第一次使用设为false，设置完成后会自动变为true)
setUp: false

# 大厅位置 (会在首次设置时自动填写)
# lobby: 

# 游戏设置
wimMoney: 30          # 赢得游戏获得的金币
killMoney: 5          # 击杀获得的金币
RealMoney: 2          # ？
gameToShutdown: 5     # 重启服务器前的游戏局数 (-1 表示不重启)

# 数据库配置
mysql:
  host: localhost     # 数据库主机地址
  port: 3306          # 数据库端口
  database: games     # 数据库名
  username: root      # 用户名
  password: ""        # 密码

# 游戏规则设置
gameRules:
  allowBreakBlocks: true    # 是否允许破坏方块
  allowPlaceBlocks: true    # 是否允许放置方块
  maxPlayers: 24            # 最大玩家数
  minPlayers: 2             # 最小开始玩家数
  gameTime: 1800            # 游戏时长(秒)